-- vector.nvim — VECTOR//OS colorscheme for neovim
-- Channel logic: cyan = functions/active, crimson = keywords/danger,
-- green = strings/success, blue = types/info, violet = builtins,
-- pink = numbers/constants, amber = enums/warnings, ember = special.
-- Active-state grammar: bold + family fill + colored underline.

local M = {}

function M.load(opts)
  opts = vim.tbl_extend("force", { transparent = false }, opts or {})

  local c = require("vector.palette")
  local b, n, br, f = c.base, c.neon, c.bright, c.fills

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.g.colors_name = "vector"

  local bg = opts.transparent and "NONE" or b.bg

  -- terminal palette (matches ghostty/vector)
  for i, hex in ipairs(c.ansi) do
    vim.g["terminal_color_" .. (i - 1)] = hex
  end

  local hl = function(group, spec)
    vim.api.nvim_set_hl(0, group, spec)
  end

  local groups = {
    -- ── editor core ──────────────────────────────────────────────
    Normal        = { fg = b.text, bg = bg },
    NormalNC      = { fg = b.text, bg = bg },
    NormalFloat   = { fg = b.text, bg = b.panel },
    FloatBorder   = { fg = n.cyan, bg = b.panel },
    FloatTitle    = { fg = n.cyan, bg = b.panel, bold = true },
    Cursor        = { fg = b.bg, bg = n.cyan },
    lCursor       = { fg = b.bg, bg = n.cyan },
    TermCursor    = { fg = b.bg, bg = n.cyan },
    CursorLine    = { bg = b.surface },
    CursorColumn  = { bg = b.surface },
    ColorColumn   = { bg = b.surface },
    LineNr        = { fg = b.dim },
    CursorLineNr  = { fg = n.cyan, bold = true },
    SignColumn    = { fg = b.dim, bg = bg },
    Folded        = { fg = b.faint, bg = b.surface, italic = true },
    FoldColumn    = { fg = b.dim, bg = bg },
    VertSplit     = { fg = b.grid },
    WinSeparator  = { fg = b.grid },
    Visual        = { bg = b.selection },
    VisualNOS     = { bg = b.selection },
    Search        = { fg = b.bg, bg = n.amber },
    IncSearch     = { fg = b.bg, bg = n.crimson },
    CurSearch     = { fg = b.bg, bg = n.crimson },
    Substitute    = { fg = b.bg, bg = n.pink },
    MatchParen    = { fg = n.cyan, bg = b.selection, bold = true },
    Whitespace    = { fg = b.grid },
    NonText       = { fg = b.grid },
    SpecialKey    = { fg = b.dim },
    EndOfBuffer   = { fg = b.bg },
    Conceal       = { fg = b.dim },
    Directory     = { fg = n.blue, bold = true },
    Title         = { fg = n.cyan, bold = true },
    ErrorMsg      = { fg = n.crimson, bold = true },
    WarningMsg    = { fg = n.amber, bold = true },
    ModeMsg       = { fg = n.cyan, bold = true },
    MoreMsg       = { fg = n.green },
    Question      = { fg = n.cyan },
    QuickFixLine  = { bg = b.selection, bold = true },
    WildMenu      = { fg = b.bg, bg = n.cyan },
    Pmenu         = { fg = b.text, bg = b.panel },
    PmenuSel      = { fg = n.cyan, bg = b.selection, bold = true },
    PmenuSbar     = { bg = b.grid },
    PmenuThumb    = { bg = b.dim },
    StatusLine    = { fg = b.faint, bg = b.surface },
    StatusLineNC  = { fg = b.dim, bg = b.surface },
    TabLine       = { fg = b.dim, bg = b.surface },
    TabLineSel    = { fg = n.cyan, bg = b.panel, bold = true, underline = true, sp = n.cyan },
    TabLineFill   = { bg = b.surface },
    WinBar        = { fg = b.faint, bg = bg },
    WinBarNC      = { fg = b.dim, bg = bg },
    SpellBad      = { undercurl = true, sp = n.crimson },
    SpellCap      = { undercurl = true, sp = n.amber },
    SpellLocal    = { undercurl = true, sp = n.cyan },
    SpellRare     = { undercurl = true, sp = n.violet },

    -- ── legacy syntax ────────────────────────────────────────────
    Comment       = { fg = b.comment, italic = true },
    Constant      = { fg = n.pink },
    String        = { fg = n.green },
    Character     = { fg = n.green },
    Number        = { fg = n.pink },
    Boolean       = { fg = n.pink, bold = true },
    Float         = { fg = n.pink },
    Identifier    = { fg = b.text },
    Function      = { fg = n.cyan },
    Statement     = { fg = n.crimson },
    Conditional   = { fg = n.crimson, italic = true },
    Repeat        = { fg = n.crimson, italic = true },
    Label         = { fg = n.crimson },
    Operator      = { fg = b.faint },
    Keyword       = { fg = n.crimson, italic = true },
    Exception     = { fg = n.crimson, bold = true },
    PreProc       = { fg = n.violet },
    Include       = { fg = n.violet },
    Define        = { fg = n.violet },
    Macro         = { fg = n.violet },
    PreCondit     = { fg = n.violet },
    Type          = { fg = n.blue },
    StorageClass  = { fg = n.blue, italic = true },
    Structure     = { fg = n.blue },
    Typedef       = { fg = n.blue },
    Special       = { fg = n.ember },
    SpecialChar   = { fg = n.ember },
    Tag           = { fg = n.cyan },
    Delimiter     = { fg = b.faint },
    SpecialComment= { fg = b.comment, bold = true },
    Debug         = { fg = n.ember },
    Underlined    = { underline = true },
    Bold          = { bold = true },
    Italic        = { italic = true },
    Error         = { fg = n.crimson, bold = true },
    Todo          = { fg = b.bg, bg = n.amber, bold = true },

    -- ── treesitter ───────────────────────────────────────────────
    ["@comment"]                = { link = "Comment" },
    ["@comment.documentation"]  = { fg = b.comment, italic = true },
    ["@comment.error"]          = { fg = b.bg, bg = n.crimson, bold = true },
    ["@comment.warning"]        = { fg = b.bg, bg = n.amber, bold = true },
    ["@comment.todo"]           = { link = "Todo" },
    ["@comment.note"]           = { fg = b.bg, bg = n.cyan, bold = true },
    ["@constant"]               = { fg = n.pink },
    ["@constant.builtin"]       = { fg = n.pink, bold = true },
    ["@constant.macro"]         = { fg = n.violet },
    ["@string"]                 = { fg = n.green },
    ["@string.documentation"]   = { fg = n.green, italic = true },
    ["@string.regexp"]          = { fg = n.ember },
    ["@string.escape"]          = { fg = n.ember, bold = true },
    ["@string.special"]         = { fg = n.ember },
    ["@string.special.symbol"]  = { fg = n.pink },
    ["@string.special.url"]     = { fg = n.blue, underline = true },
    ["@character"]              = { fg = n.green },
    ["@character.special"]      = { fg = n.ember },
    ["@number"]                 = { fg = n.pink },
    ["@number.float"]           = { fg = n.pink },
    ["@boolean"]                = { fg = n.pink, bold = true },
    ["@function"]               = { fg = n.cyan },
    ["@function.builtin"]       = { fg = n.violet },
    ["@function.call"]          = { fg = n.cyan },
    ["@function.macro"]         = { fg = n.violet },
    ["@function.method"]        = { fg = n.cyan },
    ["@function.method.call"]   = { fg = n.cyan },
    ["@constructor"]            = { fg = n.blue, bold = true },
    ["@operator"]               = { fg = b.faint },
    ["@keyword"]                = { fg = n.crimson, italic = true },
    ["@keyword.coroutine"]      = { fg = n.crimson, italic = true, bold = true },
    ["@keyword.function"]       = { fg = n.crimson, italic = true },
    ["@keyword.operator"]       = { fg = n.crimson },
    ["@keyword.import"]         = { fg = n.violet },
    ["@keyword.type"]           = { fg = n.crimson, italic = true },
    ["@keyword.modifier"]       = { fg = n.crimson, italic = true },
    ["@keyword.repeat"]         = { fg = n.crimson, italic = true },
    ["@keyword.return"]         = { fg = n.crimson, bold = true, italic = true },
    ["@keyword.debug"]          = { fg = n.ember },
    ["@keyword.exception"]      = { fg = n.crimson, bold = true },
    ["@keyword.conditional"]    = { fg = n.crimson, italic = true },
    ["@keyword.directive"]      = { fg = n.violet },
    ["@label"]                  = { fg = n.pink },
    ["@punctuation.delimiter"]  = { fg = b.faint },
    ["@punctuation.bracket"]    = { fg = b.faint },
    ["@punctuation.special"]    = { fg = n.ember },
    ["@type"]                   = { fg = n.blue },
    ["@type.builtin"]           = { fg = n.blue, italic = true },
    ["@type.definition"]        = { fg = n.blue, bold = true },
    ["@attribute"]              = { fg = n.violet },
    ["@attribute.builtin"]      = { fg = n.violet, italic = true },
    ["@property"]               = { fg = n.ice },
    ["@variable"]               = { fg = b.text },
    ["@variable.builtin"]       = { fg = n.violet, italic = true },
    ["@variable.parameter"]     = { fg = b.text, italic = true },
    ["@variable.member"]        = { fg = n.ice },
    ["@module"]                 = { fg = n.blue },
    ["@module.builtin"]         = { fg = n.violet },
    ["@tag"]                    = { fg = n.crimson },
    ["@tag.builtin"]            = { fg = n.crimson },
    ["@tag.attribute"]          = { fg = n.ice },
    ["@tag.delimiter"]          = { fg = b.faint },
    ["@markup.strong"]          = { bold = true },
    ["@markup.italic"]          = { italic = true },
    ["@markup.strikethrough"]   = { strikethrough = true },
    ["@markup.underline"]       = { underline = true },
    ["@markup.heading"]         = { fg = n.cyan, bold = true },
    ["@markup.heading.1"]       = { fg = n.cyan, bold = true },
    ["@markup.heading.2"]       = { fg = n.blue, bold = true },
    ["@markup.heading.3"]       = { fg = n.violet, bold = true },
    ["@markup.heading.4"]       = { fg = n.pink, bold = true },
    ["@markup.heading.5"]       = { fg = n.amber, bold = true },
    ["@markup.heading.6"]       = { fg = n.green, bold = true },
    ["@markup.quote"]           = { fg = b.faint, italic = true },
    ["@markup.math"]            = { fg = n.blue },
    ["@markup.link"]            = { fg = n.blue },
    ["@markup.link.label"]      = { fg = n.cyan },
    ["@markup.link.url"]        = { fg = n.blue, underline = true },
    ["@markup.raw"]             = { fg = n.green },
    ["@markup.raw.block"]       = { fg = b.text },
    ["@markup.list"]            = { fg = n.crimson },
    ["@markup.list.checked"]    = { fg = n.green },
    ["@markup.list.unchecked"]  = { fg = b.dim },
    ["@diff.plus"]              = { fg = n.green },
    ["@diff.minus"]             = { fg = n.crimson },
    ["@diff.delta"]             = { fg = n.blue },

    -- ── LSP semantic tokens ──────────────────────────────────────
    ["@lsp.type.class"]         = { link = "@type" },
    ["@lsp.type.comment"]       = {},
    ["@lsp.type.decorator"]     = { link = "@attribute" },
    ["@lsp.type.enum"]          = { fg = n.amber },
    ["@lsp.type.enumMember"]    = { fg = n.pink },
    ["@lsp.type.function"]      = { link = "@function" },
    ["@lsp.type.interface"]     = { fg = n.blue, italic = true },
    ["@lsp.type.macro"]         = { link = "@function.macro" },
    ["@lsp.type.method"]        = { link = "@function.method" },
    ["@lsp.type.namespace"]     = { link = "@module" },
    ["@lsp.type.parameter"]     = { link = "@variable.parameter" },
    ["@lsp.type.property"]      = { link = "@property" },
    ["@lsp.type.struct"]        = { link = "@type" },
    ["@lsp.type.type"]          = { link = "@type" },
    ["@lsp.type.typeParameter"] = { fg = n.blue, italic = true },
    ["@lsp.type.variable"]      = {},
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.readonly"]       = { fg = n.pink },

    -- ── diagnostics ──────────────────────────────────────────────
    DiagnosticError            = { fg = n.crimson },
    DiagnosticWarn             = { fg = n.amber },
    DiagnosticInfo             = { fg = n.blue },
    DiagnosticHint             = { fg = n.cyan },
    DiagnosticOk               = { fg = n.green },
    DiagnosticVirtualTextError = { fg = n.crimson, bg = f.crimson_bg },
    DiagnosticVirtualTextWarn  = { fg = n.amber, bg = f.amber_bg },
    DiagnosticVirtualTextInfo  = { fg = n.blue, bg = f.blue_bg },
    DiagnosticVirtualTextHint  = { fg = n.cyan, bg = b.panel },
    DiagnosticUnderlineError   = { undercurl = true, sp = n.crimson },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = n.amber },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = n.blue },
    DiagnosticUnderlineHint    = { undercurl = true, sp = n.cyan },
    DiagnosticUnnecessary      = { fg = b.dim, undercurl = true, sp = b.dim },
    DiagnosticDeprecated       = { strikethrough = true, fg = b.faint },
    LspReferenceText           = { bg = b.selection },
    LspReferenceRead           = { bg = b.selection },
    LspReferenceWrite          = { bg = b.selection, underline = true },
    LspInlayHint               = { fg = b.dim, bg = b.surface, italic = true },
    LspCodeLens                = { fg = b.dim, italic = true },
    LspSignatureActiveParameter= { fg = n.cyan, bold = true },

    -- ── diff / git ───────────────────────────────────────────────
    DiffAdd       = { bg = f.green_bg },
    DiffChange    = { bg = f.blue_bg },
    DiffDelete    = { bg = f.crimson_bg },
    DiffText      = { bg = b.selection, bold = true },
    diffAdded     = { fg = n.green },
    diffRemoved   = { fg = n.crimson },
    diffChanged   = { fg = n.blue },
    diffFile      = { fg = n.cyan },
    diffLine      = { fg = n.violet },
    GitSignsAdd         = { fg = n.green },
    GitSignsChange      = { fg = n.blue },
    GitSignsDelete      = { fg = n.crimson },
    GitSignsCurrentLineBlame = { fg = b.dim, italic = true },

    -- ── plugin: telescope / fzf-lua / snacks picker ──────────────
    TelescopeBorder        = { fg = n.cyan, bg = bg },
    TelescopePromptPrefix  = { fg = n.crimson, bold = true },
    TelescopeSelection     = { fg = n.cyan, bg = b.selection, bold = true },
    TelescopeMatching      = { fg = n.amber, bold = true },
    TelescopeTitle         = { fg = b.bg, bg = n.cyan, bold = true },
    FzfLuaBorder           = { fg = n.cyan },
    FzfLuaTitle            = { fg = b.bg, bg = n.cyan, bold = true },
    FzfLuaHeaderText       = { fg = b.faint },
    SnacksPicker           = { fg = b.text, bg = bg },
    SnacksPickerBorder     = { fg = n.cyan, bg = bg },
    SnacksPickerTitle      = { fg = b.bg, bg = n.cyan, bold = true },
    SnacksPickerMatch      = { fg = n.amber, bold = true },
    SnacksPickerCursorLine = { bg = b.selection },
    SnacksIndent           = { fg = b.grid },
    SnacksIndentScope      = { fg = b.dim },
    SnacksDashboardHeader  = { fg = n.cyan, bold = true },
    SnacksDashboardDesc    = { fg = b.faint },
    SnacksDashboardIcon    = { fg = n.crimson },
    SnacksDashboardKey     = { fg = n.amber, bold = true },
    SnacksDashboardFooter  = { fg = b.dim, italic = true },
    SnacksNotifierInfo     = { fg = n.blue, bg = b.panel },
    SnacksNotifierWarn     = { fg = n.amber, bg = b.panel },
    SnacksNotifierError    = { fg = n.crimson, bg = b.panel },
    SnacksNotifierBorderInfo  = { fg = n.blue, bg = b.panel },
    SnacksNotifierBorderWarn  = { fg = n.amber, bg = b.panel },
    SnacksNotifierBorderError = { fg = n.crimson, bg = b.panel },

    -- ── plugin: neo-tree / oil ───────────────────────────────────
    NeoTreeNormal          = { fg = b.text, bg = bg },
    NeoTreeNormalNC        = { fg = b.text, bg = bg },
    NeoTreeDirectoryName   = { fg = n.blue },
    NeoTreeDirectoryIcon   = { fg = n.blue },
    NeoTreeRootName        = { fg = n.cyan, bold = true, underline = true, sp = n.cyan },
    NeoTreeGitAdded        = { fg = n.green },
    NeoTreeGitModified     = { fg = n.blue },
    NeoTreeGitDeleted      = { fg = n.crimson },
    NeoTreeGitUntracked    = { fg = n.pink },
    NeoTreeGitConflict     = { fg = n.ember, bold = true },
    NeoTreeGitIgnored      = { fg = b.dim },
    NeoTreeIndentMarker    = { fg = b.grid },
    NeoTreeDimText         = { fg = b.dim },
    OilDir                 = { fg = n.blue, bold = true },
    OilFile                = { fg = b.text },

    -- ── plugin: cmp / blink ──────────────────────────────────────
    CmpItemAbbr            = { fg = b.text },
    CmpItemAbbrMatch       = { fg = n.cyan, bold = true },
    CmpItemAbbrMatchFuzzy  = { fg = n.cyan },
    CmpItemAbbrDeprecated  = { fg = b.faint, strikethrough = true },
    CmpItemKindFunction    = { fg = n.cyan },
    CmpItemKindMethod      = { fg = n.cyan },
    CmpItemKindVariable    = { fg = b.text },
    CmpItemKindKeyword     = { fg = n.crimson },
    CmpItemKindClass       = { fg = n.blue },
    CmpItemKindInterface   = { fg = n.blue },
    CmpItemKindModule      = { fg = n.violet },
    CmpItemKindProperty    = { fg = n.ice },
    CmpItemKindField       = { fg = n.ice },
    CmpItemKindConstant    = { fg = n.pink },
    CmpItemKindEnum        = { fg = n.amber },
    CmpItemKindSnippet     = { fg = n.green },
    CmpItemKindText        = { fg = b.faint },
    BlinkCmpMenu           = { fg = b.text, bg = b.panel },
    BlinkCmpMenuBorder     = { fg = n.cyan, bg = b.panel },
    BlinkCmpMenuSelection  = { bg = b.selection, bold = true },
    BlinkCmpLabelMatch     = { fg = n.cyan, bold = true },
    BlinkCmpDoc            = { fg = b.text, bg = b.panel },
    BlinkCmpDocBorder      = { fg = b.grid, bg = b.panel },

    -- ── plugin: which-key / flash / noice / notify ───────────────
    WhichKey               = { fg = n.cyan, bold = true },
    WhichKeyGroup          = { fg = n.blue },
    WhichKeyDesc           = { fg = b.text },
    WhichKeySeparator      = { fg = b.dim },
    FlashLabel             = { fg = b.bg, bg = n.crimson, bold = true },
    FlashMatch             = { fg = n.cyan, bg = b.selection },
    FlashCurrent           = { fg = n.amber, bg = b.selection, bold = true },
    FlashBackdrop          = { fg = b.dim },
    NoiceCmdlinePopupBorder= { fg = n.cyan },
    NoiceCmdlineIcon       = { fg = n.crimson },
    NotifyINFOBorder       = { fg = n.blue },
    NotifyINFOIcon         = { fg = n.blue },
    NotifyINFOTitle        = { fg = n.blue, bold = true },
    NotifyWARNBorder       = { fg = n.amber },
    NotifyWARNIcon         = { fg = n.amber },
    NotifyWARNTitle        = { fg = n.amber, bold = true },
    NotifyERRORBorder      = { fg = n.crimson },
    NotifyERRORIcon        = { fg = n.crimson },
    NotifyERRORTitle       = { fg = n.crimson, bold = true },

    -- ── plugin: bufferline / lazy / trouble / treesitter-context ─
    BufferLineIndicatorSelected = { fg = n.cyan },
    LazyH1                 = { fg = b.bg, bg = n.cyan, bold = true },
    LazyButton             = { fg = b.faint, bg = b.surface },
    LazyButtonActive       = { fg = b.bg, bg = n.cyan, bold = true },
    LazySpecial            = { fg = n.crimson },
    TroubleNormal          = { fg = b.text, bg = bg },
    TreesitterContext      = { bg = b.surface },
    TreesitterContextBottom= { underline = true, sp = b.grid },
    IlluminatedWordText    = { bg = b.selection },
    IlluminatedWordRead    = { bg = b.selection },
    IlluminatedWordWrite   = { bg = b.selection, underline = true },

    -- ── plugin: grapple / aerial / octo / neotest ────────────────
    GrappleCurrent         = { fg = n.crimson, bold = true },
    AerialLine             = { bg = b.selection },
    AerialGuide            = { fg = b.grid },
    OctoStateOpen          = { fg = n.green, bold = true },
    OctoStateClosed        = { fg = n.crimson, bold = true },
    OctoStateMerged        = { fg = n.violet, bold = true },
    NeotestPassed          = { fg = n.green },
    NeotestFailed          = { fg = n.crimson },
    NeotestRunning         = { fg = n.amber },
    NeotestSkipped         = { fg = b.dim },
    NeotestAdapterName     = { fg = n.violet, bold = true },
    NeotestFocused         = { bold = true, underline = true, sp = n.cyan },

    -- ── markdown / render-markdown ───────────────────────────────
    RenderMarkdownCode     = { bg = b.surface },
    RenderMarkdownCodeInline = { fg = n.green, bg = b.surface },
    RenderMarkdownH1Bg     = { fg = n.cyan, bg = b.panel, bold = true },
    RenderMarkdownH2Bg     = { fg = n.blue, bg = f.blue_bg, bold = true },
    RenderMarkdownBullet   = { fg = n.crimson },
    RenderMarkdownTableHead= { fg = n.cyan },
    RenderMarkdownTableRow = { fg = b.faint },
  }

  for group, spec in pairs(groups) do
    hl(group, spec)
  end
end

return M
