#!/usr/bin/env python3
"""regen.py — rebuild every derived port from palette/vector.json.

Derived files (never edit by hand):
  palette/vector.sh                          shell exports
  palette/vector.css                         CSS custom properties
  palette/vector.lua                         requireable Lua table
  nvim/vector.nvim/lua/vector/palette.lua    copy of the Lua table
  ghostty/themes/vector                      ghostty theme

Hand-maintained ports (grep VECTOR-PALETTE when retuning):
  tmux/vector.conf, tmux scripts, claude-code/vector-statusline.sh,
  lib/vector-components.sh, starship/vector.toml, lsd/themes/vector.yml,
  wezterm/vector.lua, borders/bordersrc
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
p = json.load(open(ROOT / "palette/vector.json"))

def hexes(group):
    return {k: v["hex"] for k, v in p[group].items() if not k.startswith("_")}

base, neon, dimn, br, fills = (
    hexes("base"), hexes("neon"), hexes("dim_neon"), hexes("bright"), hexes("fills"))
ansi = p["ansi"]

# ── vector.sh ────────────────────────────────────────────────────────────
lines = ["# vector palette — shell exports. source this from scripts.",
         "# GENERATED by scripts/regen.py from palette/vector.json — do not edit.", ""]
for d, pre in ((base, ""), (neon, ""), (dimn, "DIM_"), (br, "BR_"), (fills, "")):
    for k, v in d.items():
        lines.append(f'export VECTOR_{pre}{k.upper()}="{v}"')
(ROOT / "palette/vector.sh").write_text("\n".join(lines) + "\n")

# ── vector.css ───────────────────────────────────────────────────────────
css = [":root {", "  /* vector palette — GENERATED by scripts/regen.py */"]
for d, pre in ((base, ""), (neon, ""), (dimn, "dim-"), (br, "br-"), (fills, "")):
    for k, v in d.items():
        css.append(f"  --vector-{pre}{k.replace('_', '-')}: {v};")
css.append("}")
(ROOT / "palette/vector.css").write_text("\n".join(css) + "\n")

# ── vector.lua (+ nvim copy) ─────────────────────────────────────────────
def lua_tbl(d, ind=4):
    pad = " " * ind
    return "\n".join(f'{pad}{k} = "{v}",' for k, v in d.items())

lua = f"""-- vector palette — GENERATED by scripts/regen.py from palette/vector.json
return {{
  base = {{
{lua_tbl(base)}
  }},
  neon = {{
{lua_tbl(neon)}
  }},
  dim_neon = {{
{lua_tbl(dimn)}
  }},
  bright = {{
{lua_tbl(br)}
  }},
  fills = {{
{lua_tbl(fills)}
  }},
  ansi = {{ {", ".join(json.dumps(ansi[str(i)]) for i in range(16))} }},
}}
"""
(ROOT / "palette/vector.lua").write_text(lua)
(ROOT / "nvim/vector.nvim/lua/vector/palette.lua").write_text(lua)

# ── ghostty theme ────────────────────────────────────────────────────────
g = ["# vector — VECTOR//OS terminal theme for ghostty",
     "# GENERATED by scripts/regen.py from palette/vector.json"]
for i in range(16):
    g.append(f"palette = {i}={ansi[str(i)]}")
g += [f"background = {base['bg']}",
      f"foreground = {base['text']}",
      f"cursor-color = {neon['cyan']}",
      f"cursor-text = {base['bg']}",
      f"selection-background = {base['selection']}",
      f"selection-foreground = {base['bright']}",
      f"split-divider-color = {base['grid']}"]
(ROOT / "ghostty/themes/vector").write_text("\n".join(g) + "\n")

# ── starship palette (spliced into stowed config; no include mechanism) ────
# starship.toml has no @import, so the [palettes.vector] block is generated
# in place between VECTOR-PALETTE-START/END markers. Base tokens used for
# styling (drops the structural void/overlay/selection tones) + all neon.
STARSHIP = ROOT.parent.parent / "starship/.config/starship.toml"
star_base = [k for k in base if k not in ("overlay", "selection", "comment")]
block = ["# VECTOR-PALETTE-START — GENERATED by themes/vector/scripts/regen.py, do not edit.",
         "[palettes.vector]"]
block += [f'{k} = "{base[k]}"' for k in star_base]
block += [f'{k} = "{v}"' for k, v in neon.items()]
block.append("# VECTOR-PALETTE-END")
txt = STARSHIP.read_text().splitlines()
try:
    s = next(i for i, l in enumerate(txt) if "VECTOR-PALETTE-START" in l)
    e = next(i for i, l in enumerate(txt) if "VECTOR-PALETTE-END" in l)
    txt[s:e + 1] = block
    STARSHIP.write_text("\n".join(txt) + "\n")
    star_msg = " starship"
except StopIteration:
    star_msg = " starship(SKIPPED: markers missing)"

print("regenerated: vector.sh vector.css vector.lua nvim-palette ghostty" + star_msg)
