#!/bin/sh
set -eu

command -v lisgd >/dev/null 2>&1 || exit 0
pgrep -x lisgd >/dev/null 2>&1 && exit 0

exec lisgd \
    -d /dev/input/by-path/platform-AMDI0010:01-event \
    -w 1280 -h 800 \
    -g '3,LR,L,*,R,scrollmsg "workspace prev"' \
    -g '3,RL,R,*,R,scrollmsg "workspace next"' \
    -g '3,DU,N,*,R,scrollmsg "scale_workspace overview"' \
    -g '3,UD,N,*,R,scrollmsg "scale_workspace reset"'
